version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    links:
      - php
      - mariadb
  php:
    build:
      context: ./conf/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html  
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234rr
      MYSQL_DATABASE: owncloud
      MYSQL_USER: admin
      MYSQL_PASSWORD: rr1234

